# Generated by Django 3.0.5 on 2020-04-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='element2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element5',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element6',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element7',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element8',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='element9',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row1', to='solver.Row')),
                ('row2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row2', to='solver.Row')),
                ('row3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row3', to='solver.Row')),
                ('row4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row4', to='solver.Row')),
                ('row5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row5', to='solver.Row')),
                ('row6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row6', to='solver.Row')),
                ('row7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row7', to='solver.Row')),
                ('row8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row8', to='solver.Row')),
                ('row9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row9', to='solver.Row')),
            ],
        ),
    ]
